### ISSUE TITLE
Selected activity is not removed from the top of the list

### ISSUE THREAD

**Issue by jessstubenbord** [lm-tools/choose-your-activities#27]
The activity that you are sorting is removed from the place it was in the list rather than the top, and you are returned to the top of the page. This means that you do not have visibility of what has been removed

**Comment by lukasz-kaniowski** [comment]
we can either remove it from the top or place user in the middle of the page where the activity was in the first instance. preferences?

**Comment by jessstubenbord** [comment]
Since the user is currently returned to the top of the page when coming back to their unsorted list, and there is no order to the list currently, the sorted item should be removed from the top of the page where they can see it. This gives visibility to the activity leaving the list, which is the reason for the animation. 

The only issue with this approach is that it breaks the order of the list. I argue that this is unimportant as it is seen as a pile of activities, which is likely not showing all at once, and sorting is done on a separate screen, removing visibility of "the pile".

**Comment by nathancashmoredwp** [comment]
This has been addressed as a result of #28 but it has been noted the transition of the activity off the screen should be relative to the width of the page otherwise it is left hanging to the right of the screen.
