### ISSUE TITLE
Colour of sorted activity is not changed and it remains selectable

### ISSUE THREAD

**Issue by jessstubenbord** [lm-tools/choose-your-activities#28]
The activity that has been sorted remains blue and clickable. This could lead to confusion, especially if the activity is accidentally clicked as it is animating.

**Comment by nathancashmoredwp** [comment]
Agreed.  Intend to change so when you select the item you are returned to the unsorted activities list but the item selected is no longer clickable and has the banner colour of the appropriate category selected.
@jessstubenbord does that sound about right.

**Comment by jessstubenbord** [comment]
I think gray for the colour since at this point the more important message is that it's leaving your sorted list, rather than the category it's going to. The gray is meant to show that it is both unselectable and leaving. This is something that could definitely be up for reconsideration as the tool evolves.
