### ISSUE TITLE
The show activities dropdown is bad

### ISSUE THREAD

**Issue by jessstubenbord** [lm-tools/choose-your-activities#30]
This is a carryover issue from the design prototype. The show activities dropdown remains visible even if there are no activities under the dropdown. There is no indication of how many activities are under this dropdown. Side question: should they be on the page at all if they are under a dropdown?

**Comment by nathancashmoredwp** [comment]
Will change the following based on discussion:
* Where there are no activities under a category there will not be a show hide but instead just the content "You haven't chosen anything for this."
* Where there are activities we shall show the number of activities under that category e.g. "Show 1 activity" or "Show 2 activities"

**Comment by nathancashmoredwp** [comment]
Closing this discussion as now broken out into two separate issues for work to be carried out.  See #47 and #46
