### ISSUE TITLE
Categorisation order should be consistent across all lists

### ISSUE THREAD

**Issue by nathancashmoredwp** [lm-tools/choose-your-activities#36]
When you categorise an activity the order in which they display is inconsistent between the categorise page and the sorted list.

This is confusing when trying to find an item you have just categorised.

**Comment by lukasz-kaniowski** [comment]
@jessstubenbord how was this on the prototype? was the order done this way on purpose?

**Comment by jessstubenbord** [comment]
The reasoning behind this was as follows:

The order during categorisation is meant to map to how a user thinks about doing thing activities currently, from already ongoing to not going to happen. 

The order on the sorted list is meant to prioritise actions you're not doing yet but would potentially take up.

This could definitely cause confusion, especially on re-sorting if the user builds their mental around how the activities are categorised based on one or the other, and isn't informed enough by the other categorisation indications on the page (group headings, colour)
