### ISSUE TITLE
Activity sort animation causes viewport weirdness on mobile

### ISSUE THREAD

**Issue by slightlyamish** [lm-tools/choose-your-activities#92]
![screenshot_20170727-153041](https://user-images.githubusercontent.com/30260106/28675859-09da07fa-72e1-11e7-9f64-ff1d2fe5a5b2.png)
The animation as an activity is sorted changes the viewport on android chrome mobile. Screenshot attached

**Comment by notmymonkeys** [comment]
prove it, looks like a photoshop

**Comment by slightlyamish** [comment]
This was due to a weird browser configuration in the end, "request desktop site" was enabled
